INSERT INTO VEGGIE (NAME) VALUES ('carota');
INSERT INTO VEGGIE (NAME) VALUES ('sedano');
INSERT INTO VEGGIE (NAME) VALUES ('cipolla');
INSERT INTO VEGGIE (NAME) VALUES ('pomodoro');
INSERT INTO VEGGIE (NAME) VALUES ('basilico');
INSERT INTO VEGGIE (NAME) VALUES ('lavanda');
INSERT INTO VEGGIE (NAME) VALUES ('rosmarino');
INSERT INTO VEGGIE (NAME) VALUES ('timo');
INSERT INTO VEGGIE (NAME) VALUES ('menta');
INSERT INTO VEGGIE (NAME) VALUES ('patata');

INSERT INTO VEGASS (VEGGIE1, VEGGIE2) VALUES (3,1);
INSERT INTO VEGASS (VEGGIE1, VEGGIE2) VALUES (3,2);
INSERT INTO VEGASS (VEGGIE1, VEGGIE2) VALUES (4,5);

-- Insert seeding time by veggie name
INSERT INTO SEEDING (VEGGIE, FROM_MONTH, TO_MONTH, SEEDLINGS_DISTANCE, ROWS_DISTANCE)
SELECT VEGGIE.ID, 3, 4, 20, 35
FROM VEGGIE WHERE VEGGIE.NAME = 'cipolla';